### ISSUE TITLE
I would like to be able to cancel existing jobs

### ISSUE THREAD

**Issue by candyapplecorn** [robdmc/crontabs#11]
I was going to use your library for a project but I don't see a way to look up jobs and stop them. I looked @ the schedule library and it supports it: https://schedule.readthedocs.io/en/stable/faq.html#how-can-i-cancel-several-jobs-at-once Did I miss something in the code/documentation or is this feature not supported?

**Comment by robdmc** [comment]
You are correct.  There is no functionality baked in to stop a job.  What I usually do in my work is just use kill the process from bash (thereby stopping all jobs).  I can then restart with new job definition if I desire.  It's ugly, but easy.

**Comment by candyapplecorn** [comment]
>Think of crontabs as a quick-and-dirty solution you can throw into one-off python scripts

True to your word! TBH after completing the project, I almost wish I'd gone with a simpler library that didn't try to be a framework 😢
