### ISSUE TITLE
How does the seconds argument differ?

### ISSUE THREAD

**Issue by metaperl** [robdmc/crontabs#6]
How does the effect of the `seconds` argument to `every` differ from the seconds argument to `run` in :
    Tab(name='my_slow_job').every(seconds=20).run(my_job, 'slow', seconds=20),

as part of 
```
Cron().schedule(
    # Turn off logging for job that runs every five seconds
    Tab(name='my_fast_job', verbose=False).every(seconds=5).run(my_job, 'fast', seconds=5),

    # Go ahead and let this job emit logging messages
    Tab(name='my_slow_job').every(seconds=20).run(my_job, 'slow', seconds=20),
).go()

```

**Comment by robdmc** [comment]
Sorry.  It's been a while since I looked at crontabs.  The `seconds` argument in `run` is just an argument to the specific function I was running.  It has nothing to do with crontabs per se.

**Comment by robdmc** [comment]
Closing this for now.  If you have further questions, feel free to hit me up.
